apiVersion: v1
kind: Service
metadata:
  name: back-despachos
  namespace: despacho
  labels:
    app: back-despachos
spec:
  type: ClusterIP
  selector:
    app: back-despachos
  ports:
    - name: http
      port: 8080
      targetPort: 8080
