apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - app-secret.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - back-ventas-deployment.yaml
  - back-ventas-service.yaml
  - back-despachos-deployment.yaml
  - back-despachos-service.yaml
  - back-ventas-hpa.yaml
  - back-despachos-hpa.yaml
